name: haskell-practice
version: 0.1.0.0

dependencies:
- base >= 4.7 && < 5
- mtl >= 2.3 && < 3

library:
  source-dirs: 
  - src
  - others

executables:
  haskell-practice-exe:
    main: Main.hs
    source-dirs: app
    dependencies:
    - haskell-practice
